# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f6ec144c158a338ba348aad54ec67b0e8f12dc2e2e2cb3f46418f9db87caaa66b6091ccaa58c9674675f77ff77af122a7ea6b613065cd110e53649e00198064

test:
  secret_key_base: 7c8886a8d5cb028a98458d9fd89e8d49bdc3aaf1beda25eafe850d54202ec9f34f27c48c47bf64a23a44f02351ceab1f58c0bb11294972e11c0bad0be1b4ccf6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
